services:
  spired:
    image: 2lu3/spired:v1.0
    volumes:
      - ./data:/opt/spired/data:ro
      - ./output:/opt/spired/output
    command:
      - --fasta_file
      - data/myquery.fasta
      - --saved_folder
      - output
