services:
  spired:
    image: 2lu3/spired:latest
    volumes:
      - ./data:/opt/spired/data:ro
      - ./output:/opt/spired/output
      - spired_cache:/opt/spired/cache
    command:
      - --fasta_file
      - data/myquery.fasta
      - --saved_folder
      - output

volumes:
  spired_cache:
