name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    environment:
      name: production

    steps:
      # ソースコードをチェックアウト
      - uses: actions/checkout@v4

      # 1) Docker Hub へログイン
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # 2) 日時タグ取得
      - name: Set IMAGE_DATE
        id: date
        run: |
          echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      # 3) ビルド＆プッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            2lu3/spired:latest
            2lu3/spired:${{ steps.date.outputs.date }}
